import { useEffect, useState } from 'react';
import { api } from '../../api/client';
import type { ReportRecord, ReportType } from '../../api/domain';
import { DialogShell } from '../../components/modals/DialogShell';
import { PlusIcon } from '../../icons';

interface ReportsPageProps {
  showToast: (msg: string) => void;
}

export function ReportsPage({ showToast }: ReportsPageProps) {
  const [reports, setReports] = useState<ReportRecord[] | null>(null);
  const [statusFilter, setStatusFilter] = useState<'all' | 'pending' | 'approved'>('all');
  const [open, setOpen] = useState(false);
  const [reportType, setReportType] = useState<ReportType>('attendance');
  const [details, setDetails] = useState('');

  async function load() {
    const query = statusFilter === 'all' ? '' : `?status=${statusFilter}`;
    const data = await api.get<ReportRecord[]>(`/admin/reports${query}`);
    setReports(data);
  }

  useEffect(() => {
    load();
  }, [statusFilter]);

  async function submitGenerate() {
    await api.post('/admin/reports', { report_type: reportType, details: details || undefined });
    setOpen(false);
    setDetails('');
    showToast('Report generated');
    load();
  }

  async function approve(r: ReportRecord) {
    await api.post(`/admin/reports/${r.report_id}/approve`);
    showToast(`${r.report_type} report approved`);
    load();
  }

  return (
    <>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 16 }}>
        <select className="input" style={{ maxWidth: 180 }} value={statusFilter} onChange={(e) => setStatusFilter(e.target.value as typeof statusFilter)}>
          <option value="all">All statuses</option>
          <option value="pending">Pending</option>
          <option value="approved">Approved</option>
        </select>
        <div style={{ flex: 1 }} />
        <button type="button" className="btn btn-primary" onClick={() => setOpen(true)}>
          <PlusIcon />
          Generate report
        </button>
      </div>

      <div className="card elev-sm" style={{ padding: 0, overflow: 'hidden' }}>
        <table className="table">
          <thead>
            <tr>
              <th>Type</th>
              <th>Generated by</th>
              <th>Generated</th>
              <th>Status</th>
              <th style={{ width: 110 }}>Actions</th>
            </tr>
          </thead>
          <tbody>
            {reports?.map((r) => (
              <tr key={r.report_id}>
                <td style={{ fontWeight: 600, textTransform: 'capitalize' }}>{r.report_type}</td>
                <td style={{ opacity: 0.75 }}>{r.generated_by_name}</td>
                <td style={{ opacity: 0.65 }}>{new Date(r.generated_date).toLocaleString()}</td>
                <td><span className={r.status === 'approved' ? 'tag tag-success' : 'tag tag-warning'}>{r.status}</span></td>
                <td>
                  {r.status === 'pending' && (
                    <button type="button" className="btn btn-secondary" onClick={() => approve(r)}>Approve</button>
                  )}
                </td>
              </tr>
            ))}
            {reports && reports.length === 0 && (
              <tr><td colSpan={5} style={{ opacity: 0.6, textAlign: 'center', padding: 24 }}>No reports found.</td></tr>
            )}
          </tbody>
        </table>
      </div>

      {open && (
        <DialogShell
          title="Generate report"
          onClose={() => setOpen(false)}
          actions={
            <>
              <button type="button" className="btn btn-secondary" onClick={() => setOpen(false)}>Cancel</button>
              <button type="button" className="btn btn-primary" onClick={submitGenerate}>Generate</button>
            </>
          }
        >
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            <div className="field">
              <label>Report type</label>
              <select className="input" value={reportType} onChange={(e) => setReportType(e.target.value as ReportType)}>
                <option value="attendance">Attendance</option>
                <option value="performance">Performance</option>
                <option value="training">Training</option>
              </select>
            </div>
            <div className="field">
              <label>Details (optional)</label>
              <textarea className="input" style={{ minHeight: 70 }} value={details} onChange={(e) => setDetails(e.target.value)} />
            </div>
          </div>
        </DialogShell>
      )}
    </>
  );
}
